spring:
  cloud:
    stream:

      kafka:
        binder:
          brokers: localhost:9092

      bindings:
        greetings-out:
          destination: greetings
          contentType: application/json

        part-greetings-out:
          destination: partGreetings
          contentType: application/json
          producer:
#            partitionKeyExpression: payload.id
#            partitionKeyExpression: "0"
            partitionKeyExpression: payload.id