spring:
  cloud:
    stream:

      kafka:
        binder:
          brokers: localhost:9092
          auto-add-partitions: true

      bindings:
        greetings-out:
          destination: greetings
          contentType: application/json

        part-greetings-out:
          destination: partGreetings
          contentType: application/json
          producer:
            partitionKeyExpression: payload.id
            partitionCount: ${INSTANCE_COUNT:2}